CREATE_TABLE_USERS = """
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

# CREATE_TABLE_PATIENT = """
# CREATE TABLE IF NOT EXISTS patient (
#     id SERIAL PRIMARY KEY
# )
# """

# CREATE_TABLE_PSYCHOLOGIST = """
# CREATE TABLE IF NOT EXISTS psychologist (
#     id SERIAL PRIMARY KEY,
#     email VARCHAR(100) NOT NULL,
#     full_name VARCHAR(100) NOT NULL,
#     city VARCHAR(50) NOT NULL,
#     is_staff BIT NOT NULL,
#     is_superuser BIT NOT NULL,
#     is_active BIT NOT NULL,
#     data_joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP
# )
# """

CREATE_TABLE_REQUESTS_APPOINTMENTS = """
CREATE TABLE IF NOT EXISTS requests_appointments (
    id SERIAL PRIMARY KEY,
    agenda_day_hour_id INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    reason VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agenda_day_hour_id) REFERENCES agenda_day_hour (id)
)
"""

CREATE_TABLE_APPOINTMENTS = """
CREATE TABLE IF NOT EXISTS appointments (
    id SERIAL PRIMARY KEY,
    agenda_day_hour_id INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    reason VARCHAR(50) NOT NULL,
    anonymous BIT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (agenda_day_hour_id) REFERENCES agenda_day_hour (id)
)
"""

CREATE_AGENDA_TABLE = """
CREATE TABLE IF NOT EXISTS agenda (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

CREATE_TABLE_AGENDA_DAY_HOUR = """
CREATE TABLE IF NOT EXISTS agenda_day_hour (
    id SERIAL PRIMARY KEY,
    agenda_id INTEGER NOT NULL,
    start_date_time TIMESTAMP NOT NULL,
    end_date_time TIMESTAMP NOT NULL,
    FOREIGN KEY (agenda_id) REFERENCES agenda (id)
)
"""